item_types:
    sylius_product:
        min_selected: 1
        max_selected: 0
        preview:
            template: '%netgen_content_browser.sylius_product.default_item_template%'
        columns:
            name:
                name: columns.name
                value_provider: name
            product_id:
                name: columns.sylius_product.product_id
                value_provider: sylius_product\product_id
        default_columns:
            - name
            - product_id
