parameters:
    netgen_content_browser.backend.sylius_product.class: Netgen\Bundle\ContentBrowserBundle\Backend\SyliusProductBackend

    netgen_content_browser.item_configurator.handler.sylius_product.class: Netgen\Bundle\ContentBrowserBundle\Item\Configurator\Handler\SyliusProductConfiguratorHandler
    netgen_content_browser.template_value_provider.sylius_product.class: Netgen\Bundle\ContentBrowserBundle\Item\Renderer\TemplateValueProvider\SyliusProductTemplateValueProvider

    netgen_content_browser.column_value_provider.sylius_product.product_id.class: Netgen\Bundle\ContentBrowserBundle\Item\ColumnProvider\ColumnValueProvider\SyliusProduct\ProductId

services:
    netgen_content_browser.backend.sylius_product:
        class: "%netgen_content_browser.backend.sylius_product.class%"
        arguments:
            - "@sylius.repository.taxon"
            - "@sylius.repository.product"
        tags:
            - { name: netgen_content_browser.backend, value_type: sylius_product }

    netgen_content_browser.item_configurator.handler.sylius_product:
        class: "%netgen_content_browser.item_configurator.handler.sylius_product.class%"
        tags:
            - { name: netgen_content_browser.item_configurator.handler, value_type: sylius_product }

    netgen_content_browser.template_value_provider.sylius_product:
        class: "%netgen_content_browser.template_value_provider.sylius_product.class%"
        tags:
            - { name: netgen_content_browser.template_value_provider, value_type: sylius_product }

    netgen_content_browser.column_value_provider.sylius_product.product_id:
        class: "%netgen_content_browser.column_value_provider.sylius_product.product_id.class%"
        tags:
            - { name: netgen_content_browser.column_value_provider, identifier: sylius_product\product_id }
